apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stac-creator.fullname" . }}
  labels:
    {{- include "stac-creator.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "stac-creator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "stac-creator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stac-creator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NATS_HOST
              value: {{ .Values.nats.hostname | default "nats" | quote }}
            - name: NATS_PORT
              value: {{ .Values.nats.port | default "4222" | quote }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: S3_ENDPOINT
              value: {{ .Values.s3.endpoint }}
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket }}
            - name: S3_STAC_PATH
              value: {{ .Values.s3.stacPath }}
            - name: S3_IMAGERY_PATH
              value: {{ .Values.s3.imageryPath }}
            - name: PYTHONWARNINGS
              value: ignore
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
