name: Chart Lintering and Validation

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.0.1
        with:
          command: lint

  validation:
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Kubernetes Validator
        uses: desaintmartin/helm-kubeval-action@master
        with:
          path: charts
